name: plotly_dart
description: A pure Dart wrapper of Plotly js
version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  web: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
  lints: ^4.0.0
